from pathlib import Path
s = Path("qsirch_gui.py").read_text(encoding="utf-8")
required = [
    'APP_VERSION = "v10.19"',
    'COMPACT_HEIGHT = 132',
    'self.hint=QLabel(',
    'hasattr(self, "hint")',
    'self.tabs.addTab(conn, "Connection")',
    'self.tabs.addTab(behavior, "Appearance / Behavior")',
    'self.tabs.addTab(paths, "Path Mapping")',
    'self.tabs.addTab(rules_tab, "Rules")',
    'self.tabs.addTab(hist, "History")',
    'class HistoryStore:',
    'class HotkeyManager:',
    'RegisterHotKey',
    '"show_in_taskbar"',
    'add_results',
    'import_machine_to_current',
    'def ssl_toggled',
    'highlight_matches',
    'settings_stylesheet',
    'DONATION_URL',
    'self.tabs.addTab(about, "About")',
    'open_donation',
    'ssl_verify',
    'HTTPS port changed to 443',
    'HTTPS certificate verification turned off',
    'openb = QPushButton("Open")',
    'self.preview_btn=QPushButton("Preview")',
    'client.thumbnail(preview_item)',
    'def similar(self, item_id',
    'def more_like_this(self):',
    'def parse_search_text',
    'def client_filter_items',
    'self.exact_match=QCheckBox("Exact")',
    'self.standard_window = QCheckBox("Use standard resizable Windows frame")',
    'self.allow_download = QCheckBox("Show Download button")',
    'QTextEdit#previewText',
    'self.filters_btn=QPushButton("Filters")',
    'self.help_btn=QPushButton("?")',
    'self.sidebar.setObjectName("sidebar")',
    'self.favorite_title = QLabel("Favorites")',
    'def refresh_favorites_panel(self):',
    'def show_search_help(self):',
    'def apply_window_layout_mode(self):',
    'self.preview_pixmap = None',
    'def scale_preview_image(self):',
    '"standard_window": True',
    'def local_file_preview(self, item):',
    'def build_preview_data(self, preview_item, request_id):',
    'QPixmap(image_path)',
    'TEXT_PREVIEW_EXTS',
    'FILE_TYPE_FILTERS',
    '("PowerPoint", "All",',
    'opts["exts"]',
    'MAX_TEXT_PREVIEW_BYTES',
    '#cardStandard',
    '"source_filter": "__this__"',
    'row.mouseDoubleClickEvent = open_row',
    'child.setAttribute(Qt.WA_TransparentForMouseEvents, True)',
    'clear_current_machine(self.clear_starred_history.isChecked())',
    'button.setText("★" if starred else "☆")',
    'visibility_rules',
    'def is_visibility_hidden',
    'windows_identity_names',
    'self.preview_visible = False',
    'self.preview_workers.append(worker)',
    '"preview_pane": False',
    '"result_view": "details"',
    'self.view_mode=QComboBox()',
    'def configure_result_list_for_view(self):',
    'QListWidget.IconMode',
    'def add_icon_result_item(self, item, history_entry=None):',
    'def quick_filter_changed(self):',
    'self.category_filter=QComboBox()',
    'self.favorite_list = QListWidget()',
    'self.favorite_list.itemClicked.connect(self.open_item)',
    'def has_favorites_to_show(self):',
    'fav=m.addAction',
    'display_path',
    'QSystemTrayIcon',
    'setSizeHint',
]
missing = [x for x in required if x not in s]
if missing:
    raise SystemExit("Missing required v10 source markers: " + repr(missing))
print("v10.19 source verification passed.")
