from pathlib import Path
s = Path("qsirch_gui.py").read_text(encoding="utf-8")
required = [
    'APP_VERSION = "v10.11"',
    'COMPACT_HEIGHT = 132',
    'self.hint=QLabel(',
    'hasattr(self, "hint")',
    'self.tabs.addTab(conn, "Connection")',
    'self.tabs.addTab(behavior, "Appearance / Behavior")',
    'self.tabs.addTab(paths, "Path Mapping")',
    'self.tabs.addTab(excl, "Exclusions")',
    'self.tabs.addTab(visible, "Visibility")',
    'self.tabs.addTab(hist, "History")',
    'class HistoryStore:',
    'class HotkeyManager:',
    'RegisterHotKey',
    '"show_in_taskbar"',
    'add_results',
    'import_machine_to_current',
    'def ssl_toggled',
    'highlight_matches',
    'settings_stylesheet',
    'DONATION_URL',
    'self.tabs.addTab(about, "About")',
    'open_donation',
    'ssl_verify',
    'HTTPS port changed to 443',
    'HTTPS certificate verification turned off',
    'openb = QPushButton("Open")',
    'self.preview_btn=QPushButton("Preview")',
    'client.thumbnail(preview_item)',
    'clear_current_machine(self.clear_starred_history.isChecked())',
    'button.setText("★" if starred else "☆")',
    'visibility_rules',
    'def is_visibility_hidden',
    'windows_identity_names',
    'self.preview_visible = False',
    'self.preview_workers.append(worker)',
    '"preview_pane": False',
    'display_path',
    'QSystemTrayIcon',
    'setSizeHint',
]
missing = [x for x in required if x not in s]
if missing:
    raise SystemExit("Missing required v10 source markers: " + repr(missing))
print("v10.11 source verification passed.")
