<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>PyQsirchgui</AssemblyName>
    <RootNamespace>PyQsirchgui.Windows</RootNamespace>
    <ApplicationIcon />
  </PropertyGroup>
</Project>
